// 실제 API 연결 전까지 화면 설계와 상태 흐름을 맞추기 위한 관제 목업 데이터이다.
export const liveSnapshot = {
  timestamp: "2026-07-27T10:30:00.000+09:00",
  source: "lidar-pc-01",
  status: "wrong-way-level-2",
  totalObjects: 6,
  movingVehicleCount: 4,
  normalMovingVehicleCount: 3,
  wrongWayCount: 1,
  pedestrianCount: 1,
  processingTimeMs: 8.518,
};

export const detectedObjects = [
  {
    monitoringZoneId: "roundabout-1",
    trackId: "8b630000-0000-0000-0000-000000000000",
    type: "normal-driving",
    warningLevel: 0,
    confidence: 1,
    zoneId: "Z469",
    message: "정주행",
    speedKmh: 25.41,
    objectClass: 1,
    description: "Normal",
  },
  {
    monitoringZoneId: "roundabout-1",
    trackId: "91630000-0000-0000-0000-000000000000",
    type: "normal-driving",
    warningLevel: 0,
    confidence: 1,
    zoneId: "Z170",
    message: "정주행",
    speedKmh: 11.63,
    objectClass: 1,
    description: "Normal",
  },
  {
    monitoringZoneId: "roundabout-1",
    trackId: "b6630000-0000-0000-0000-000000000000",
    type: "normal-driving",
    warningLevel: 0,
    confidence: 1,
    zoneId: "Z274",
    message: "정주행",
    speedKmh: 14.72,
    objectClass: 1,
    description: "Normal",
  },
  {
    monitoringZoneId: "roundabout-2",
    trackId: "f7263000-0000-0000-0000-000000000000",
    type: "wrong-way-level-2",
    warningLevel: 2,
    confidence: 0.95,
    zoneId: "Z455",
    message: "역주행 2차 감지",
    speedKmh: 13.32,
    objectClass: 1,
    description: "Wrong-way driving detected",
  },
  {
    monitoringZoneId: "roundabout-2",
    trackId: "ped-20300000-0000-0000-0000-000000000000",
    type: "pedestrian-entered",
    warningLevel: 0,
    confidence: 0.92,
    zoneId: "Z261",
    message: "보행자 진입",
    speedKmh: 4.05,
    objectClass: 7,
    description: "Pedestrian entered roundabout area",
  },
];

export const realtimeEvents = [
  {
    id: "EVT-20260727-004",
    monitoringZoneId: "roundabout-2",
    type: "wrong-way-level-2",
    title: "역주행 2차 감지",
    message: "Z455 구역에서 비정상 이탈 방향 객체 감지",
    time: "10:30:00",
    status: "NEW",
  },
  {
    id: "EVT-20260727-003",
    monitoringZoneId: "roundabout-2",
    type: "pedestrian-entered",
    title: "보행자 진입",
    message: "회전교차로 내부 보행자 객체 감지",
    time: "10:29:43",
    status: "MONITORING",
  },
  {
    id: "EVT-20260727-002",
    monitoringZoneId: "roundabout-1",
    type: "normal-driving",
    title: "정상 통과",
    message: "Z469 구역 차량 통과 상태 갱신",
    time: "10:29:38",
    status: "UPDATED",
  },
  {
    id: "EVT-20260727-001",
    monitoringZoneId: "roundabout-1",
    type: "situation-ended",
    title: "상황 종료",
    message: "이전 역주행 이벤트 정상 복귀 처리",
    time: "10:27:12",
    status: "CLOSED",
  },
];

export const eventHistory = [
  {
    id: "EVT-20260727-004",
    occurredAt: "2026-07-27 10:30:00",
    type: "wrong-way-level-2",
    zoneId: "Z455",
    trackId: "f7263000",
    speedKmh: 13.32,
    status: "NEW",
    message: "역주행 2차 감지",
    description: "회전교차로 이탈 후 비정상 이동 감지",
  },
  {
    id: "EVT-20260727-003",
    occurredAt: "2026-07-27 10:29:43",
    type: "pedestrian-entered",
    zoneId: "Z261",
    trackId: "ped-20300000",
    speedKmh: 4.05,
    status: "MONITORING",
    message: "보행자 진입",
    description: "회전교차로 내부 보행자 진입 알림",
  },
  {
    id: "EVT-20260727-002",
    occurredAt: "2026-07-27 10:27:12",
    type: "situation-ended",
    zoneId: "Z327",
    trackId: "ended-81760000",
    speedKmh: 8.68,
    status: "CLOSED",
    message: "상황 종료",
    description: "역주행 객체 정상 주행 전환",
  },
  {
    id: "EVT-20260727-001",
    occurredAt: "2026-07-27 09:54:20",
    type: "wrong-way-level-1",
    zoneId: "Z327",
    trackId: "81760000",
    speedKmh: 10.21,
    status: "DONE",
    message: "역주행 1차 감지",
    description: "회전교차로 내부 역주행 발생",
  },
];

export const statisticsSeries = [
  { label: "00시", vehicles: 118, wrongWay: 0, pedestrians: 1 },
  { label: "03시", vehicles: 64, wrongWay: 0, pedestrians: 0 },
  { label: "06시", vehicles: 204, wrongWay: 1, pedestrians: 2 },
  { label: "09시", vehicles: 486, wrongWay: 1, pedestrians: 3 },
  { label: "12시", vehicles: 532, wrongWay: 2, pedestrians: 5 },
  { label: "15시", vehicles: 468, wrongWay: 1, pedestrians: 4 },
  { label: "18시", vehicles: 612, wrongWay: 3, pedestrians: 6 },
  { label: "21시", vehicles: 275, wrongWay: 1, pedestrians: 2 },
];

export const zoneStatistics = [
  { zone: "Z170", wrongWay: 1, vehicles: 522 },
  { zone: "Z261", wrongWay: 2, vehicles: 684 },
  { zone: "Z327", wrongWay: 3, vehicles: 748 },
  { zone: "Z455", wrongWay: 4, vehicles: 391 },
  { zone: "Z469", wrongWay: 1, vehicles: 812 },
];

// 관제 구역 단위로 CCTV, 외부 Lanelet 코드, 장비 상태를 묶는다.
// cameras 배열에 항목을 추가하면 대시보드의 CCTV 영역도 별도 코드 수정 없이 늘어난다.
export const monitoringZones = [
  {
    id: "roundabout-1",
    name: "회전교차로 1",
    source: "lidar-pc-01",
    laneletZoneIds: ["Z469", "Z170", "Z274"],
    cameras: [
      {
        id: "CCTV-01",
        label: "회전교차로 1 CCTV",
        location: "진입로 및 회전교차로",
        status: "online",
      },
    ],
    snapshot: {
      status: "normal-driving",
      totalObjects: 3,
      movingVehicleCount: 3,
      normalMovingVehicleCount: 3,
      wrongWayCount: 0,
      pedestrianCount: 0,
      processingTimeMs: 7.842,
      source: "lidar-pc-01",
    },
    devices: [
      {
        name: "LIDAR-PC-01",
        type: "라이다 PC",
        status: "online",
        health: "정상",
        ip: "192.168.0.60",
        lastSeen: "방금 전",
      },
      {
        name: "CONTROL-BOARD-01",
        type: "통합제어보드",
        status: "online",
        health: "정상",
        ip: "192.168.0.20:5000",
        lastSeen: "1분 전",
      },
      {
        name: "CCTV-01",
        type: "CCTV",
        status: "online",
        health: "정상",
        ip: "영상 연동 예정",
        lastSeen: "방금 전",
      },
      {
        name: "SPEAKER-01-1",
        type: "스피커 1",
        status: "online",
        health: "제어 대기",
        ip: "제어보드 연동",
        lastSeen: "1분 전",
      },
      {
        name: "SPEAKER-01-2",
        type: "스피커 2",
        status: "online",
        health: "제어 대기",
        ip: "제어보드 연동",
        lastSeen: "1분 전",
      },
      {
        name: "VMS-01-1",
        type: "전광판 1",
        status: "warning",
        health: "점검 필요",
        ip: "제어보드 연동",
        lastSeen: "5분 전",
      },
      {
        name: "VMS-01-2",
        type: "전광판 2",
        status: "online",
        health: "제어 대기",
        ip: "제어보드 연동",
        lastSeen: "1분 전",
      },
      {
        name: "BARRIER-01",
        type: "차단기",
        status: "online",
        health: "제어 대기",
        ip: "제어보드 연동",
        lastSeen: "1분 전",
      },
    ],
  },
  {
    id: "roundabout-2",
    name: "회전교차로 2",
    source: "lidar-pc-02",
    laneletZoneIds: ["Z455", "Z261", "Z327"],
    cameras: [
      {
        id: "CCTV-02",
        label: "회전교차로 2 CCTV",
        location: "진입로 및 차단기",
        status: "online",
      },
    ],
    snapshot: {
      status: "wrong-way-level-2",
      totalObjects: 2,
      movingVehicleCount: 1,
      normalMovingVehicleCount: 0,
      wrongWayCount: 1,
      pedestrianCount: 1,
      processingTimeMs: 8.518,
      source: "lidar-pc-02",
    },
    devices: [
      {
        name: "LIDAR-PC-02",
        type: "라이다 PC",
        status: "online",
        health: "정상",
        ip: "대기",
        lastSeen: "방금 전",
      },
      {
        name: "CONTROL-BOARD-02",
        type: "통합제어보드",
        status: "offline",
        health: "연결 전",
        ip: "대기",
        lastSeen: "미연결",
      },
      {
        name: "CCTV-02",
        type: "CCTV",
        status: "online",
        health: "정상",
        ip: "영상 연동 예정",
        lastSeen: "방금 전",
      },
      ...["스피커 1", "스피커 2", "전광판 1", "전광판 2", "차단기"].map((type, index) => ({
        name: `ZONE-02-CONTROL-${index + 1}`,
        type,
        status: "offline",
        health: "제어보드 연결 전",
        ip: "제어보드 연동",
        lastSeen: "미연결",
      })),
    ],
  },
];

// 기존 장비 페이지는 동일한 관제 구역 데이터를 화면 형식에 맞춰 재사용한다.
export const deviceGroups = monitoringZones.map((zone) => ({
  zone: zone.name,
  devices: zone.devices,
}));
